### ISSUE TITLE
Cannot find module '@angular/http'.

### ISSUE THREAD

**Issue by danielmenezesbr** [sudheerj/generator-jhipster-primeng#37]
Steps to reproduce (JHipster 4.14.1 with Angular 5):

yo jhipster-primeng
...
```
ERROR in [at-loader] ./src/main/webapp/app/primeng/fileupload/fileupload/backend/fake-backend.ts:19:110
    TS2307: Cannot find module '@angular/http'.
```
...

**Comment by sudheerj** [comment]
I can't replicate the issue. Have you done npm install before doing npm start. Please comment here to reopen the issue if you still replicate the issue.

**Comment by danielmenezesbr** [comment]
Yes. I do yarn install before yarn start. generator-jhipster-primeng is compatible with Angular 5?

Angular 5 moved @angular/http to @angular/common/http. Why the generator[1] point to @angular/http and @angular/http/testing?

If you want I can create a Vagrantfile to show how to reproduce it.

Thanks

[1] https://github.com/sudheerj/generator-jhipster-primeng/blob/1207fd72183229cabc272b43d8aca2c5e65a469f/generators/app/templates/src/main/webapp/app/primeng/fileupload/fileupload/backend/fake-backend.ts#L19-L20

**Comment by sudheerj** [comment]
It is deprecated in Angular 5 version but it shouldn't throw an error by saying that not able to find module. The issue is not faced by anyother as well. The current module uses Angular 5.2.1 version. 

![image](https://user-images.githubusercontent.com/3127317/38195728-a45880ec-36b1-11e8-8f5f-2bbeddc534c8.png)

It will be updated soon. Did you follow the same instructions.

**Comment by ValoData** [comment]
I had the same issue and needed to install the http module explicitly

npm i @angular/http
