### ISSUE TITLE
this.getJhipsterAppConfig is not a function

### ISSUE THREAD

**Issue by amatosg** [sudheerj/generator-jhipster-primeng#75]
the module is not working anymore with jhipster 6.1.0 :(

```
TypeError: this.getJhipsterAppConfig is not a function 
at module.exports.readConfig (node_modules/generator-jhipster-primeng/generators/app/index.js:33:47)
```

**Comment by erickjx** [comment]
Hi, i apply fix #73 :
this.getJhipsterAppConfig();   ->   this.getAllJhipsterConfig();

I was have some troubles before fix because jhipster 6.1.0 need Angular 8 , then i apply [this fix from primeng](https://github.com/primefaces/primeng/commit/39bb387c3139c918c759a9cc1a4afbb8b5890f7b) in treedemo.component.ts:

@ViewChild('expandingTree') -> @ViewChild('expandingTree', { static: false })

An rename css file to scss because i use SASS.

**Comment by sudheerj** [comment]
@amatosg @erickjx Thanks for reporting. There will be a new release in the next week.

@erickjx Is this issue specific to tree component? I think there won't be any issue with slider component.

**Comment by erickjx** [comment]
Hi, i taken from fix update to Angular 8 in treetable/treetable.ts  the definition of __ViewChild__ was changed in Angular 8.

**Comment by sudheerj** [comment]
@erickjx Okay, I will check that. Thanks

**Comment by sudheerj** [comment]
Did you guys face the below issue,
```

[INFO] Module parse failed: Unexpected token (1:0)
[INFO] You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
[INFO] > .slider-width, .input-width{
[INFO] |     width:'14em';
[INFO] | }
```

**Comment by erickjx** [comment]
Erase character "|" in css style class...

**Comment by sudheerj** [comment]
JHipster-PrimeNG 3.0.0 is available with all the changes. Thanks.

**Comment by sudheerj** [comment]
@erickjx We will check them in a minor release with other changes.
